### ISSUE TITLE
Possible to get the brotli node module updated to 67?

### ISSUE THREAD

**Issue by h0h0h0** [shelfio/aws-lambda-brotli-unpacker#43]
I am attempting to use the shelfio/aws-lambda-libreoffice on node 11. I downgraded to 8 as a workaround but would like to know how I can recompile brotli/ itlorb.node module.

```
node_1  | Error: The module '/app/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node'
node_1  | was compiled against a different Node.js version using
node_1  | NODE_MODULE_VERSION 57. This version of Node.js requires
node_1  | NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
node_1  | the module (for instance, using `npm rebuild` or `npm install`).
node_1  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:846:18)
node_1  |     at Module.load (internal/modules/cjs/loader.js:672:32)
node_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
node_1  |     at Function.Module._load (internal/modules/cjs/loader.js:604:3)
node_1  |     at Module.require (internal/modules/cjs/loader.js:711:19)
node_1  |     at require (internal/modules/cjs/helpers.js:14:16)
node_1  |     at Object.<anonymous> (/app/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/index.js:8:16)
node_1  |     at Module._compile (internal/modules/cjs/loader.js:805:30)
node_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
node_1  |     at Module.load (internal/modules/cjs/loader.js:672:32)```

**Comment by h0h0h0** [comment]
(P.S. Thank you so so so much)

**Comment by vladgolubev** [comment]
@h0h0h0 you're welcome, Shaun!

As far as I know, AWS Lambda does not support node 11 runtime. May I ask where do you run your code? 
If I update `itorb` module it will make library incompatible with current Lambda environment, which it is intended for. 
As an option you can stay on 8.x, or fork a library which will be independent of Lambda limitations (not only node 8 but hard-coded `/tmp` folder as well).

Let me know what do you think

**Comment by vladgolubev** [comment]
FYI the nodejs10.x runtime is now using Node 10.16, which has native Brotli support.
